### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-django#20]
It looks like quite a few of our tests are failing.

Most of the issues appear to be centered around calculating the size of a collection `len(app.groups)`, etc. I'm filing this issue on this Django repo as this is where the customer is tracking it, so feel free to open up another more detailed issue on the python SDK repo if you prefer ^^

If you checkout this library, then run:

```console
$ python setup.py develop
$ python setup.py testdep
$ python setup.py test  # assuming you've supplied the correct environment variables
```

You'll see quite a few test failures. Here's the output I'm getting now:

```console
$ python setup.py test
running test
coverage run --source=django_stormpath manage.py test --settings=testproject.settings testapp && coverage html
Creating test database for alias 'default'...
F.........FE.EF..F...
======================================================================
ERROR: test_deleteing_a_group (testapp.tests.TestUserAndGroups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdegges/Dropbox/Code/stormpath/stormpath-django/testproject/testapp/tests.py", line 42, in tearDown
    g.delete()
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/resources/base.py", line 260, in delete
    self._store.delete_resource(self.href)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/data_store.py", line 157, in delete_resource
    self.executor.delete(href)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/http.py", line 167, in delete
    return self.request('DELETE', url)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/http.py", line 156, in request
    self.raise_error(r)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/http.py", line 115, in raise_error
    raise Error({'developerMessage': ret}, http_status=r.status_code)
Error: {u'status': 404, u'developerMessage': u'The requested resource does not exist.', u'message': u'The requested resource does not exist.', u'code': 404, u'moreInfo': u'mailto:support@stormpath.com'}

======================================================================
ERROR: test_group_creation_error_on_local_db (testapp.tests.TestUserAndGroups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdegges/Dropbox/Code/stormpath/stormpath-django/testproject/testapp/tests.py", line 42, in tearDown
    g.delete()
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/resources/base.py", line 260, in delete
    self._store.delete_resource(self.href)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/data_store.py", line 157, in delete_resource
    self.executor.delete(href)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/http.py", line 167, in delete
    return self.request('DELETE', url)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/http.py", line 156, in request
    self.raise_error(r)
  File "/Users/rdegges/.virtualenvs/stormpath-django/lib/python2.7/site-packages/stormpath-1.3.3-py2.7.egg/stormpath/http.py", line 115, in raise_error
    raise Error({'developerMessage': ret}, http_status=r.status_code)
Error: {u'status': 404, u'developerMessage': u'The requested resource does not exist.', u'message': u'The requested resource does not exist.', u'code': 404, u'moreInfo': u'mailto:support@stormpath.com'}

======================================================================
FAIL: test_saving_user_form (testapp.tests.TestForms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdegges/Dropbox/Code/stormpath/stormpath-django/testproject/testapp/tests.py", line 375, in test_saving_user_form
    self.assertEqual(form.errors, 'hi')
AssertionError: {'username': [u"{u'status': 404, u'developerMessage': u'The requested resource does not exist.', u'message': u'The requested resource does not exist.', u'code': 404, u'moreInfo': u'mailto:support@stormpath.com'}"], 'email': [u"{u'status': 404, u'developerMessage': u'The requested resource does not exist.', u'message': u'The requested resource does not exist.', u'code': 404, u'moreInfo': u'mailto:support@stormpath.com'}"]} != 'hi'

======================================================================
FAIL: test_deleteing_a_group (testapp.tests.TestUserAndGroups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdegges/Dropbox/Code/stormpath/stormpath-django/testproject/testapp/tests.py", line 239, in test_deleteing_a_group
    self.assertEqual(0, len(self.app.groups))
AssertionError: 0 != 1

======================================================================
FAIL: test_group_creation_errors_are_handled (testapp.tests.TestUserAndGroups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdegges/Dropbox/Code/stormpath/stormpath-django/testproject/testapp/tests.py", line 192, in test_group_creation_errors_are_handled
    self.assertEqual(2, len(self.app.groups))
AssertionError: 2 != 1

======================================================================
FAIL: test_saving_group_membership (testapp.tests.TestUserAndGroups)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdegges/Dropbox/Code/stormpath/stormpath-django/testproject/testapp/tests.py", line 267, in test_saving_group_membership
    self.assertEqual(0, len(a.group_memberships))
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 20 tests in 87.022s

FAILED (failures=4, errors=2)
Destroying test database for alias 'default'...
make: *** [test] Error 1
```

Hey @avojnovicDk, would you please prioritize this above all other tasks atm? We have a customer who is deploying a large project using our Django library, and some of the failing tests below are blockers for them.

**Comment by avojnovicDk** [comment]
Hey @rdegges! I'll get right on it...

**Comment by rdegges** [comment]
Thanks @avojnovicDk !

**Comment by rdegges** [comment]
All fixed =) Merged in the fixes from @avojnovicDk
