### ISSUE TITLE
Editing a Django Group's permissions fails with 'Group with that name already exists'

### ISSUE THREAD

**Issue by davidmarquis** [stormpath/stormpath-django#27]
When editing an existing Group object in the Django admin panel, the following exception arises:

```
 Traceback (most recent call last):
File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/options.py", line 583, in wrapper
  return self.admin_site.admin_view(view)(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
  response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
  response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 206, in inner
  return view(request, *args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1456, in change_view
  return self.changeform_view(request, object_id, form_url, extra_context)
File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py", line 29, in _wrapper
  return bound_func(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
  response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py", line 25, in bound_func
  return func.__get__(self, type(self))(*args2, **kwargs2)
File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
  return func(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1404, in changeform_view
  self.save_model(request, new_object, form, not add)
File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1045, in save_model
  obj.save()
File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
  force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python3.4/site-packages/django/db/models/base.py", line 613, in save_base
  update_fields=update_fields)
File "/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
  response = receiver(signal=self, sender=sender, **named)
File "/usr/local/lib/python3.4/site-packages/django_stormpath/models.py", line 267, in save_group_to_stormpath
  raise IntegrityError(e)
django.db.utils.IntegrityError: {'message': 'Group with that name already exists.  Please choose another name.', 'code': 2001, 'developerMessage': 'Group with that name already exists.  Please choose another name.', 'moreInfo': 'http://docs.stormpath.com/errors/2001', 'status': 409}
```

The workaround is to manually fiddle with the group in the Stormpath admin UI, but that is not very practical long term...

**Comment by davidmarquis** [comment]
Additional traceback info (logged just above the other traceback): 

```
web_1 | Traceback (most recent call last):
web_1 |   File "/usr/local/lib/python3.4/site-packages/django_stormpath/models.py", line 265, in save_group_to_stormpath
web_1 |     APPLICATION.groups.create({'name': instance.name})
web_1 |   File "/usr/local/lib/python3.4/site-packages/stormpath/resources/base.py", line 464, in create
web_1 |     params=params
web_1 |   File "/usr/local/lib/python3.4/site-packages/stormpath/data_store.py", line 145, in create_resource
web_1 |     data = self.executor.post(href, data, params=params)
web_1 |   File "/usr/local/lib/python3.4/site-packages/stormpath/http.py", line 173, in post
web_1 |     return self.request('POST', url, data=dumps(data), params=params)
web_1 |   File "/usr/local/lib/python3.4/site-packages/stormpath/http.py", line 165, in request
web_1 |     self.raise_error(r)
web_1 |   File "/usr/local/lib/python3.4/site-packages/stormpath/http.py", line 124, in raise_error
web_1 |     raise Error({'developerMessage': ret}, http_status=r.status_code)
web_1 | stormpath.error.Error: {'message': 'Group with that name already exists.  Please choose another name.', 'code': 2001, 'developerMessage': 'Group with that name already exists.  Please choose another name.', 'moreInfo': 'http://docs.stormpath.com/errors/2001', 'status': 409}
```

**Comment by davidmarquis** [comment]
Should be fixed on the next release
